---
name: "Create apt repos"

"on":
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-unsigned-repo:
    name: Create an unsigned dev repo on purpose
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create repo
        uses: jinnatar/actions-aptly-repo@fix_1
        with:
          name: demo
          artifact_name: unsigned-repo
          repo_url: https://repo.example.com
          repos: |
              noble,stable,\"amd64,arm64\",false,debs/stable-ubuntu-24.04-*-unknown-linux-gnu/*.deb
              bookworm,stable,\"amd64,arm64\",false,debs/stable-debian-12-*-unknown-linux-gnu/*.deb
      - name: Check repo.list
        shell: bash
        run: |
          cat demo.list
  create-unsigned-accident:
    name: Create an unsigned dev repo by mistake
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create repo
        uses: jinnatar/actions-aptly-repo@v2
        with:
          name: demo
          artifact_name: accidental-repo
          repos: |
              noble,stable,\"amd64,arm64\",false,debs/stable-ubuntu-24.04-*-unknown-linux-gnu/*.deb
              bookworm,stable,\"amd64,arm64\",false,debs/stable-debian-12-*-unknown-linux-gnu/*.deb
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEYTYPO }}"
          gpg_passphrase: "${{ secrets.PASSPHRASETYPO }}"
  create-combined-demo-repo:
    name: Create combined demo repo
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create repo
        uses: jinnatar/actions-aptly-repo@v2
        with:
          name: demo
          artifact_name: combo-repo
          repos: |
              noble,stable,\"amd64,arm64\",false,debs/stable-ubuntu-24.04-*-unknown-linux-gnu/*.deb
              jammy,stable,\"amd64,arm64\",false,debs/stable-ubuntu-22.04-*-unknown-linux-gnu/*.deb
              noble,nightly,\"amd64,arm64\",false,debs/nightly-ubuntu-24.04-*-unknown-linux-gnu/*.deb
              bookworm,stable,\"amd64,arm64\",false,debs/stable-debian-12-*-unknown-linux-gnu/*.deb
              bookworm,nightly,\"amd64,arm64\",false,debs/nightly-debian-12-*-unknown-linux-gnu/*.deb
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
          gpg_passphrase: "${{ secrets.PASSPHRASE }}"

  create-split-demo-repo:
    name: Create split demo repo
    strategy:
      matrix:
        prefix:
          - name: ubuntu
            repos: |
              noble,stable,\"amd64,arm64\",false,debs/stable-ubuntu-24.04-*-unknown-linux-gnu/*.deb
              jammy,stable,\"amd64,arm64\",false,debs/stable-ubuntu-22.04-*-unknown-linux-gnu/*.deb
              noble,nightly,\"amd64,arm64\",false,debs/nightly-ubuntu-24.04-*-unknown-linux-gnu/*.deb
          - name: debian
            repos: |
              bookworm,stable,\"amd64,arm64\",false,debs/stable-debian-12-*-unknown-linux-gnu/*.deb
              bookworm,nightly,\"amd64,arm64\",false,debs/nightly-debian-12-*-unknown-linux-gnu/*.deb
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create repo
        uses: jinnatar/actions-aptly-repo@v2
        with:
          name: kanidm-demo
          prefix: "${{ matrix.prefix.name }}"
          repos: "${{ matrix.prefix.repos }}"
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
          gpg_passphrase: "${{ secrets.PASSPHRASE }}"
  extend-demo-repo:
    name: Extend an existing repo
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Only needed in development mode when the import key does not match our demo signing key.
      - name: Read import GPG key
        id: get_import_key
        run: |
          echo 'gpg_public_key<<EOF' >> $GITHUB_OUTPUT
          cat kanidm_ppa.key >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create repo
        uses: jinnatar/actions-aptly-repo@v2
        with:
          name: kanidm-demo
          artifact_name: extended-repo-snapshot
          repo_url: https://kanidm.github.io/kanidm_ppa
          repos: |
            noble,stable,\"amd64,arm64\",true,debs/stable-ubuntu-24.04-*-unknown-linux-gnu/*.deb
            jammy,stable,\"amd64,arm64\",true,debs/stable-ubuntu-22.04-*-unknown-linux-gnu/*.deb
            noble,nightly,\"amd64,arm64\",false,debs/nightly-ubuntu-24.04-*-unknown-linux-gnu/*.deb
            bookworm,stable,\"amd64,arm64\",true,debs/stable-debian-12-*-unknown-linux-gnu/*.deb
            bookworm,nightly,\"amd64,arm64\",false,debs/nightly-debian-12-*-unknown-linux-gnu/*.deb
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
          gpg_passphrase: "${{ secrets.PASSPHRASE }}"
          import_gpg_key: "${{ steps.get_import_key.outputs.gpg_public_key }}"
  ourobouros-demo-repo:
    # This is a silly demo of the previous extended repo eating itself as an import.
    # The point is to prove that a CI run that doesn't change anything, "works",
    # and just an import without new packages does as well.
    name: Extend an existing extended repo
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create repo
        uses: jinnatar/actions-aptly-repo@v2
        with:
          name: kanidm-demo
          artifact_name: ouroboros-repo-snapshot
          repo_url: https://kanidm.github.io/kanidm_ppa
          repos: |
            noble,stable,\"amd64,arm64\",true,no-debs
            jammy,stable,\"amd64,arm64\",true,no-debs
            noble,nightly,\"amd64,arm64\",false,debs/nightly-ubuntu-24.04-*-unknown-linux-gnu/*.deb
            bookworm,stable,\"amd64,arm64\",true,debs/stable-debian-12-*-unknown-linux-gnu/*.deb
            bookworm,nightly,\"amd64,arm64\",false,debs/nightly-debian-12-*-unknown-linux-gnu/*.deb
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
          gpg_passphrase: "${{ secrets.PASSPHRASE }}"

  create-key-export-demos:
    name: Create key export demos
    strategy:
      matrix:
        gpg_export_name: [repo.asc, repo.gpg]
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create repo
        uses: jinnatar/actions-aptly-repo@v2
        with:
          name: kanidm-demo
          repo_url: https://repo.example.com
          artifact_name: ${{ format('key-export-snapshot-{0}', matrix.gpg_export_name) }}
          repos: |
            bookworm,stable,\"amd64,arm64\",false,debs/stable-debian-12-*-unknown-linux-gnu/*.deb
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
          gpg_passphrase: "${{ secrets.PASSPHRASE }}"
          gpg_export_name: "${{ matrix.gpg_export_name }}"
      - name: Check repo.list
        shell: bash
        run: |
          cat kanidm-demo.list
